# IntelliJ Ultimate feature
# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);




### Registration
POST {{host}}:8112/register
Content-Type: application/json

{
  "email": "test@gladysz.me",
  "password": "pass123",
  "confirmPassword": "pass123"
}


### Authorization by token, part 1. Retrieve and save token.
POST {{host}}:8112/auth
Content-Type: application/json

{
  "email": "test@gladysz.me",
  "password": "pass123"
}

> {% client.global.set("auth_token", response.body.token); %}

### Authorization by token, part 2. Use token to authorize.
GET {{host}}:8112/helloSecured2
Authorization: Bearer {{auth_token}}



### Authorization by token, part 2. Use token to authorize.
GET {{host}}:8112/hello

###
